#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

usage() {
  cat >&2 <<'USAGE'
Usage:
  scripts/pkg69_run_evidence_gate_from_bundles.sh <bundle-dir-or-parent> [...]

Finds PKG-69 evidence bundles, maps each bundle scenario to the matching
PKG69_*_EVIDENCE variable and runs scripts/pkg69_operational_evidence_gate.sh.

Each bundle must contain evidence.md and MANIFEST.tsv generated by
scripts/pkg69_bundle_evidence.sh or scripts/pkg69_collect_host_evidence.sh.

Closure is still controlled by the gate:
- set PKG69_REQUIRE_REAL_EVIDENCE=true to fail when any required scenario is missing;
- set PKG69_REQUIRE_CLOSURE_ACCEPTED=true and PKG69_ACCEPT_CLOSURE=true only after review.
USAGE
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi
if [[ "$#" -lt 1 ]]; then
  usage
  exit 64
fi

scenario_env_name() {
  case "$1" in
    windows-server) printf 'PKG69_WINDOWS_SERVER_EVIDENCE\n' ;;
    windows-desktop) printf 'PKG69_WINDOWS_DESKTOP_EVIDENCE\n' ;;
    linux-debian) printf 'PKG69_LINUX_DEBIAN_EVIDENCE\n' ;;
    linux-rhel) printf 'PKG69_LINUX_RHEL_EVIDENCE\n' ;;
    docker-runtime) printf 'PKG69_DOCKER_RUNTIME_EVIDENCE\n' ;;
    kubernetes-rbac) printf 'PKG69_KUBERNETES_RBAC_EVIDENCE\n' ;;
    proxy-tls) printf 'PKG69_PROXY_TLS_EVIDENCE\n' ;;
    clock-skew) printf 'PKG69_CLOCK_SKEW_EVIDENCE\n' ;;
    permission-ebpf) printf 'PKG69_PERMISSION_EBPF_EVIDENCE\n' ;;
    reboot-during-collection) printf 'PKG69_REBOOT_EVIDENCE\n' ;;
    disk-full) printf 'PKG69_DISK_FULL_EVIDENCE\n' ;;
    high-volume-overhead) printf 'PKG69_HIGH_VOLUME_EVIDENCE\n' ;;
    relay-hub-direct-hosts) printf 'PKG69_RELAY_HUB_DIRECT_EVIDENCE\n' ;;
    remote-update-rollback) printf 'PKG69_REMOTE_UPDATE_ROLLBACK_EVIDENCE\n' ;;
    *) return 1 ;;
  esac
}

scenario_from_manifest() {
  local manifest="$1"
  awk -F '\t' 'NR == 2 { print $1 }' "$manifest"
}

find_bundle_dirs() {
  local input="$1"
  if [[ -f "$input/MANIFEST.tsv" && -f "$input/evidence.md" ]]; then
    printf '%s\n' "$input"
    return
  fi
  find "$input" -type f -name MANIFEST.tsv -print | while IFS= read -r manifest; do
    local dir
    dir="$(dirname "$manifest")"
    if [[ -f "$dir/evidence.md" ]]; then
      printf '%s\n' "$dir"
    fi
  done
}

bundle_list="$(mktemp /tmp/aiceberg_pkg69_bundles.XXXXXX)"
trap 'rm -f "$bundle_list"' EXIT

for input in "$@"; do
  if [[ ! -d "$input" ]]; then
    echo "bundle input is not a directory: $input" >&2
    exit 65
  fi
  find_bundle_dirs "$input" >>"$bundle_list"
done

if [[ ! -s "$bundle_list" ]]; then
  echo "no evidence bundles found" >&2
  exit 66
fi

sort -u "$bundle_list" >"$bundle_list.sorted"
mv "$bundle_list.sorted" "$bundle_list"

while IFS= read -r bundle_dir; do
  scenario="$(scenario_from_manifest "$bundle_dir/MANIFEST.tsv")"
  if [[ -z "$scenario" ]]; then
    echo "bundle scenario is blank: $bundle_dir" >&2
    exit 67
  fi
  if ! env_name="$(scenario_env_name "$scenario")"; then
    echo "unknown PKG-69 scenario in bundle: $scenario ($bundle_dir)" >&2
    exit 68
  fi
  current_value=""
  eval "current_value=\${$env_name:-}"
  if [[ -n "$current_value" && "$current_value" != "$bundle_dir/evidence.md" ]]; then
    echo "duplicate evidence for $scenario: $current_value and $bundle_dir/evidence.md" >&2
    exit 69
  fi
  export "$env_name=$bundle_dir/evidence.md"
  printf 'mapped\t%s\t%s\t%s\n' "$scenario" "$env_name" "$bundle_dir/evidence.md" >&2
done <"$bundle_list"

scripts/pkg69_operational_evidence_gate.sh
