#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

usage() {
  cat >&2 <<'USAGE'
Usage:
  scripts/pkg69_run_evidence_gate_from_bundles.sh <bundle-dir-or-parent> [...]

Finds PKG-69 evidence bundles, maps each bundle scenario to the matching
PKG69_*_EVIDENCE variable and runs scripts/pkg69_operational_evidence_gate.sh.

Each bundle must contain evidence.md, MANIFEST.tsv and PROVENANCE.tsv generated by
scripts/pkg69_bundle_evidence.sh or scripts/pkg69_collect_host_evidence.sh.
The runner validates bundle integrity with the SHA256/size recorded in the
bundle MANIFEST.tsv and validates bundle provenance before mapping evidence to
the gate.

Closure is still controlled by the gate:
- set PKG69_REQUIRE_REAL_EVIDENCE=true to fail when any required scenario is missing;
- set PKG69_REQUIRE_CLOSURE_ACCEPTED=true and PKG69_ACCEPT_CLOSURE=true only after review.
USAGE
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi
if [[ "$#" -lt 1 ]]; then
  usage
  exit 64
fi

scenario_env_name() {
  case "$1" in
    windows-server) printf 'PKG69_WINDOWS_SERVER_EVIDENCE\n' ;;
    windows-desktop) printf 'PKG69_WINDOWS_DESKTOP_EVIDENCE\n' ;;
    linux-debian) printf 'PKG69_LINUX_DEBIAN_EVIDENCE\n' ;;
    linux-rhel) printf 'PKG69_LINUX_RHEL_EVIDENCE\n' ;;
    docker-runtime) printf 'PKG69_DOCKER_RUNTIME_EVIDENCE\n' ;;
    kubernetes-rbac) printf 'PKG69_KUBERNETES_RBAC_EVIDENCE\n' ;;
    proxy-tls) printf 'PKG69_PROXY_TLS_EVIDENCE\n' ;;
    clock-skew) printf 'PKG69_CLOCK_SKEW_EVIDENCE\n' ;;
    permission-ebpf) printf 'PKG69_PERMISSION_EBPF_EVIDENCE\n' ;;
    reboot-during-collection) printf 'PKG69_REBOOT_EVIDENCE\n' ;;
    disk-full) printf 'PKG69_DISK_FULL_EVIDENCE\n' ;;
    high-volume-overhead) printf 'PKG69_HIGH_VOLUME_EVIDENCE\n' ;;
    relay-hub-direct-hosts) printf 'PKG69_RELAY_HUB_DIRECT_EVIDENCE\n' ;;
    remote-update-rollback) printf 'PKG69_REMOTE_UPDATE_ROLLBACK_EVIDENCE\n' ;;
    *) return 1 ;;
  esac
}

scenario_from_manifest() {
  local manifest="$1"
  awk -F '\t' 'NR == 2 { print $1 }' "$manifest"
}

manifest_field() {
  local manifest="$1"
  local field="$2"
  awk -F '\t' -v field="$field" 'NR == 2 { print $field }' "$manifest"
}

file_sha256() {
  shasum -a 256 "$1" | awk '{ print $1 }'
}

file_size_bytes() {
  wc -c <"$1" | tr -d ' '
}

evidence_field() {
  local path="$1"
  local field="$2"
  sed -n "s/^- ${field}:[[:space:]]*//p" "$path" | head -n 1
}

provenance_field() {
  local provenance="$1"
  local key="$2"
  awk -F '\t' -v key="$key" 'NR > 1 && $1 == key { print $2; exit }' "$provenance"
}

resolve_relative_path() {
  local base_dir="$1"
  local value="$2"
  if [[ "$value" = /* ]]; then
    printf '%s\n' "$value"
  else
    printf '%s/%s\n' "$base_dir" "$value"
  fi
}

verify_bundle_manifest() {
  local bundle_dir="$1"
  local manifest="$bundle_dir/MANIFEST.tsv"
  local provenance="$bundle_dir/PROVENANCE.tsv"
  local evidence="$bundle_dir/evidence.md"
  local expected_header
  local expected_provenance_header
  local expected_template_value
  local expected_evidence_sha
  local expected_evidence_bytes
  local expected_artifact_value
  local expected_artifact_sha
  local expected_artifact_bytes
  local expected_created_at_utc
  local actual_evidence_sha
  local actual_evidence_bytes
  local line_count
  local artifact_value
  local artifact_path
  local actual_artifact_sha
  local actual_artifact_bytes
  local provenance_scenario
  local provenance_created_at_utc
  local provenance_artifact_file
  local provenance_evidence_file
  local provenance_tool
  local provenance_tool_version

  expected_header="scenario	template	sha256	bytes	artifact	artifact_sha256	artifact_bytes	created_at_utc"
  if [[ "$(head -n 1 "$manifest")" != "$expected_header" ]]; then
    echo "bundle manifest header mismatch: $manifest" >&2
    exit 70
  fi
  line_count="$(wc -l <"$manifest" | tr -d ' ')"
  if [[ "$line_count" != "2" ]]; then
    echo "bundle manifest must contain exactly one evidence row: $manifest" >&2
    exit 77
  fi
  if [[ ! -f "$provenance" ]]; then
    echo "bundle provenance missing: $provenance" >&2
    exit 81
  fi
  expected_provenance_header="key	value"
  if [[ "$(head -n 1 "$provenance")" != "$expected_provenance_header" ]]; then
    echo "bundle provenance header mismatch: $provenance" >&2
    exit 82
  fi

  expected_template_value="$(manifest_field "$manifest" 2)"
  expected_evidence_sha="$(manifest_field "$manifest" 3)"
  expected_evidence_bytes="$(manifest_field "$manifest" 4)"
  expected_artifact_value="$(manifest_field "$manifest" 5)"
  expected_artifact_sha="$(manifest_field "$manifest" 6)"
  expected_artifact_bytes="$(manifest_field "$manifest" 7)"
  expected_created_at_utc="$(manifest_field "$manifest" 8)"
  provenance_tool="$(provenance_field "$provenance" bundle_tool)"
  provenance_tool_version="$(provenance_field "$provenance" bundle_tool_version)"
  provenance_scenario="$(provenance_field "$provenance" scenario)"
  provenance_created_at_utc="$(provenance_field "$provenance" created_at_utc)"
  provenance_evidence_file="$(provenance_field "$provenance" evidence_file)"
  provenance_artifact_file="$(provenance_field "$provenance" artifact_file)"

  if [[ ! "$expected_created_at_utc" =~ ^[0-9]{8}T[0-9]{6}Z$ ]]; then
    echo "bundle manifest created_at_utc must use YYYYMMDDTHHMMSSZ: $manifest" >&2
    exit 78
  fi
  if [[ -z "$expected_template_value" || "$expected_template_value" == "-" || "$(basename "$expected_template_value")" != "$(basename "$evidence")" ]]; then
    echo "bundle manifest template does not match evidence file: $bundle_dir" >&2
    exit 80
  fi
  if [[ "$provenance_tool" != "scripts/pkg69_bundle_evidence.sh" || "$provenance_tool_version" != "1" ]]; then
    echo "bundle provenance tool mismatch: $bundle_dir" >&2
    exit 83
  fi
  if [[ "$provenance_scenario" != "$(scenario_from_manifest "$manifest")" ]]; then
    echo "bundle provenance scenario mismatch: $bundle_dir" >&2
    exit 84
  fi
  if [[ "$provenance_created_at_utc" != "$expected_created_at_utc" ]]; then
    echo "bundle provenance created_at_utc mismatch: $bundle_dir" >&2
    exit 85
  fi
  if [[ "$provenance_evidence_file" != "$(basename "$evidence")" ]]; then
    echo "bundle provenance evidence file mismatch: $bundle_dir" >&2
    exit 86
  fi

  actual_evidence_sha="$(file_sha256 "$evidence")"
  actual_evidence_bytes="$(file_size_bytes "$evidence")"

  if [[ -z "$expected_evidence_sha" || "$expected_evidence_sha" == "-" || "$actual_evidence_sha" != "$expected_evidence_sha" ]]; then
    echo "bundle evidence sha256 mismatch: $bundle_dir" >&2
    exit 71
  fi
  if [[ -z "$expected_evidence_bytes" || "$expected_evidence_bytes" == "-" || "$actual_evidence_bytes" != "$expected_evidence_bytes" ]]; then
    echo "bundle evidence size mismatch: $bundle_dir" >&2
    exit 72
  fi

  artifact_value="$(evidence_field "$evidence" "Evidencia bruta anexada")"
  if [[ -z "$artifact_value" ]]; then
    echo "bundle evidence raw artifact is blank: $bundle_dir" >&2
    exit 73
  fi
  if [[ -z "$expected_artifact_value" || "$expected_artifact_value" == "-" || "$(basename "$expected_artifact_value")" != "$(basename "$artifact_value")" ]]; then
    echo "bundle manifest artifact does not match evidence raw artifact: $bundle_dir" >&2
    exit 79
  fi
  if [[ "$provenance_artifact_file" != "$artifact_value" ]]; then
    echo "bundle provenance artifact file mismatch: $bundle_dir" >&2
    exit 87
  fi
  artifact_path="$(resolve_relative_path "$(dirname "$evidence")" "$artifact_value")"
  if [[ ! -e "$artifact_path" ]]; then
    echo "bundle raw artifact not found: $artifact_path" >&2
    exit 74
  fi

  actual_artifact_sha="$(file_sha256 "$artifact_path")"
  actual_artifact_bytes="$(file_size_bytes "$artifact_path")"

  if [[ -z "$expected_artifact_sha" || "$expected_artifact_sha" == "-" || "$actual_artifact_sha" != "$expected_artifact_sha" ]]; then
    echo "bundle artifact sha256 mismatch: $bundle_dir" >&2
    exit 75
  fi
  if [[ -z "$expected_artifact_bytes" || "$expected_artifact_bytes" == "-" || "$actual_artifact_bytes" != "$expected_artifact_bytes" ]]; then
    echo "bundle artifact size mismatch: $bundle_dir" >&2
    exit 76
  fi
}

find_bundle_dirs() {
  local input="$1"
  if [[ -f "$input/MANIFEST.tsv" && -f "$input/evidence.md" ]]; then
    printf '%s\n' "$input"
    return
  fi
  find "$input" -type f -name MANIFEST.tsv -print | while IFS= read -r manifest; do
    local dir
    dir="$(dirname "$manifest")"
    if [[ -f "$dir/evidence.md" ]]; then
      printf '%s\n' "$dir"
    fi
  done
}

bundle_list="$(mktemp /tmp/aiceberg_pkg69_bundles.XXXXXX)"
trap 'rm -f "$bundle_list"' EXIT

for input in "$@"; do
  if [[ ! -d "$input" ]]; then
    echo "bundle input is not a directory: $input" >&2
    exit 65
  fi
  find_bundle_dirs "$input" >>"$bundle_list"
done

if [[ ! -s "$bundle_list" ]]; then
  echo "no evidence bundles found" >&2
  exit 66
fi

sort -u "$bundle_list" >"$bundle_list.sorted"
mv "$bundle_list.sorted" "$bundle_list"

while IFS= read -r bundle_dir; do
  verify_bundle_manifest "$bundle_dir"
  scenario="$(scenario_from_manifest "$bundle_dir/MANIFEST.tsv")"
  if [[ -z "$scenario" ]]; then
    echo "bundle scenario is blank: $bundle_dir" >&2
    exit 67
  fi
  if ! env_name="$(scenario_env_name "$scenario")"; then
    echo "unknown PKG-69 scenario in bundle: $scenario ($bundle_dir)" >&2
    exit 68
  fi
  current_value=""
  eval "current_value=\${$env_name:-}"
  if [[ -n "$current_value" && "$current_value" != "$bundle_dir/evidence.md" ]]; then
    echo "duplicate evidence for $scenario: $current_value and $bundle_dir/evidence.md" >&2
    exit 69
  fi
  export "$env_name=$bundle_dir/evidence.md"
  printf 'mapped\t%s\t%s\t%s\n' "$scenario" "$env_name" "$bundle_dir/evidence.md" >&2
done <"$bundle_list"

scripts/pkg69_operational_evidence_gate.sh
